"""add_missing_user_columns

Revision ID: 548698174f4d
Revises: 3b888db4b382
Create Date: 2026-06-04 00:32:01.969107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548698174f4d'
down_revision: Union[str, None] = '3b888db4b382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_documents_author', 'documents', ['author'], unique=False)
    op.create_index('idx_documents_source_domain', 'documents', ['source_domain'], unique=False)
    op.create_index('idx_documents_status_created', 'documents', ['status', 'created_at'], unique=False)
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('entities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_entities_deleted_at'), 'entities', ['deleted_at'], unique=False)
    op.add_column('feedback', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('feedback', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_feedback_deleted_at'), 'feedback', ['deleted_at'], unique=False)
    op.add_column('ingest_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ingest_jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_ingest_jobs_created_at', 'ingest_jobs', ['created_at'], unique=False)
    op.create_index('idx_ingest_jobs_document_id', 'ingest_jobs', ['document_id'], unique=False)
    op.create_index('idx_ingest_jobs_status', 'ingest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_deleted_at'), 'ingest_jobs', ['deleted_at'], unique=False)
    op.create_index('idx_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.add_column('reset_requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('reset_requests', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_reset_requests_deleted_at'), 'reset_requests', ['deleted_at'], unique=False)
    op.create_index('idx_sessions_updated_at', 'sessions', ['updated_at'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_updated_at', table_name='sessions')
    op.drop_index(op.f('ix_reset_requests_deleted_at'), table_name='reset_requests')
    op.drop_column('reset_requests', 'deleted_at')
    op.drop_column('reset_requests', 'updated_at')
    op.drop_index('idx_messages_session_created', table_name='messages')
    op.drop_index(op.f('ix_ingest_jobs_deleted_at'), table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_status', table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_document_id', table_name='ingest_jobs')
    op.drop_index('idx_ingest_jobs_created_at', table_name='ingest_jobs')
    op.drop_column('ingest_jobs', 'deleted_at')
    op.drop_column('ingest_jobs', 'updated_at')
    op.drop_index(op.f('ix_feedback_deleted_at'), table_name='feedback')
    op.drop_column('feedback', 'deleted_at')
    op.drop_column('feedback', 'updated_at')
    op.drop_index(op.f('ix_entities_deleted_at'), table_name='entities')
    op.drop_column('entities', 'deleted_at')
    op.drop_column('entities', 'updated_at')
    op.drop_index('idx_documents_status_created', table_name='documents')
    op.drop_index('idx_documents_source_domain', table_name='documents')
    op.drop_index('idx_documents_author', table_name='documents')
    # ### end Alembic commands ###
